networks:
  django:
    driver: bridge

volumes:
  pg_data: null
  pycache: null


services:
  nginx:
    networks:
      - django
    ports:
      - ${PORT:-8001}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./resources:/usr/share/nginx/html/resources/
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    depends_on:
      - web

  web:
    networks:
      - django
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.web
    restart: always
    command: sh resources/scripts/entrypoint.sh
    volumes:
      - .:/code
      - pycache:/var/cache/pycache
    depends_on:
      - postgres_db
    
  postgres_db:
    networks:
      - django
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data
    
  